apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gal-alon-nginx-ingress
  namespace: app-ga
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: /app
            pathType: Prefix
            backend:
              service:
                name: gal-alon-nginx-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-kube-prometheus-prometheus
                port:
                  number: 9090
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: prometheus-grafana  # Ensure this matches your Grafana service name
                port:
                  number: 80  # This should be the port exposed by the service
